include::chapter-base.adoc[]
== Techniques & bonnes pratiques

=== KISS, YAGNI & DRY

Quelques principes populaires qui circulent dans les communautés de développeurs :

* **K**eep **I**t **S**tupid **S**imple : Le plus simple, le mieux.
Faire simple n’est cependant pas toujours facile.
* **Y**ou **A**in’t **G**onna **N**eed **I**t : N’ajouter que du code utile dans le présent.
Les prédictions sur le futur peuvent se révéler fausses et la conception qui a été faites "en prévision de" peut faire obstacle une fois le futur devenu présent.
* **D**on’t **R**epeat **Y**ourself : La duplication est mal vue parmi les développeurs, et amène plusieurs problèmes :
** C’est plus de travail, il faut écrire, tester et maintenir plusieurs fois le même code
** En cas de bug, il faut corriger à de multiples endroits, certains pouvant être oubliés

C’est cette même simplicité que l’on retrouve dans deux des douze principes du *Manifeste Agile* :

* Our highest priority is to satisfy the customer through early and continuous delivery of [.underline]#*valuable*# software
* Simplicity [the art of maximizing the amount of work not done] is essential.
